spring:
  application:
    name: formula-service

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    locations:
      - classpath:db/migration

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${RDS_USERNAME:local}
    password: ${RDS_PASSWORD:local}
    url: jdbc:mysql://${RDS_ENDPOINT:localhost}:3307/formula?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false&rewriteBatchedStatements=true
    hikari:
      maximum-pool-size: 32

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        open-in-view: false

  data:
    redis:
      port: ${REDIS_PORT}
      host: ${REDIS_HOST}

  jwt:
    secret: ${SECRET}
    access-token-expiration: ${ACCESS-TOKEN-EXPIRATION}
    refresh-token-expiration: ${REFRESH-TOKEN-EXPIRATION}
    filter:
      include-paths:
        - /api/**
      exclude-paths:
        - /api/v1/auth/**


  mail:
    host: smtp.naver.com
    port: ${NAVER_MAIL_PORT}
    username: ${NAVER_ID}
    password: ${NAVER_PW}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true
            required: true
          connectionTimeout: ${TIMEOUT}
          timeout: ${TIMEOUT}
          writeTimeout: ${TIMEOUT}
        debug: true

logging:
  level:
    com.optional.formula.common.filter.JwtAuthenticationFilter: DEBUG
    com.optional.formula.common.resolver.CurrentUserArgumentResolver: DEBUG